### ISSUE TITLE
Multiple specific addresses error

### ISSUE THREAD

**Issue by haosb** [purelb/purelb#2]
Hi, I have a little issue. I need to specify specific addresses, not a range. I tried to use this configuration:
```
apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
  local:
    v4pool:
      subnet: "10.129.0.0/24"
      pool: "10.129.0.29,10.129.0.34"
      aggregation: /32
```
But it throws an error.
![image](https://user-images.githubusercontent.com/114342765/231454928-2d4c3aed-cad4-4f38-92ad-60635248eda8.png)

And I have a question, I'm trying to use PureLB on my Bare Metal Selfhosted Cluster for automatically assign external IP for a service, but I want to auto reassign IP if one of node with ext IP down. It is possible with PureLB?

**Comment by ahmetzyanov** [comment]
Stuck with the same problem too

**Comment by caboteria** [comment]
Hi! You should be able to use multiple ranges like so:
```
apiVersion: purelb.io/v1
kind: ServiceGroup
metadata:
  name: default
  namespace: purelb
spec:
  local:
    v4pools:
    - subnet: "10.129.0.0/24"
      pool: "10.129.0.29"
      aggregation: /32
    - subnet: "10.129.0.0/24"
      pool: "10.129.0.34"
      aggregation: /32
```
I just noticed that we didn't update the docs when we added that feature, so I'll do that.
